{{- if and .Values.aws.staticCredentials.enabled (not .Values.aws.staticCredentials.existingSecret) -}}
{{- if or .Values.aws.staticCredentials.accessKeyId .Values.aws.staticCredentials.secretAccessKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bolometer.awsSecretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bolometer.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.staticCredentials.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.staticCredentials.secretAccessKey | quote }}
{{- end }}
{{- end }}
